language: node_js

node_js:
  - "4.2"
  - "5.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - ffmpeg

sudo: false

services:
  - mongodb

before_script:
  - npm install electron-prebuilt -g
  - npm run build

after_failure:
  - cat test1/logs/all-logs.log
  - cat test2/logs/all-logs.log
  - cat test3/logs/all-logs.log
  - cat test4/logs/all-logs.log
  - cat test5/logs/all-logs.log
  - cat test6/logs/all-logs.log
