listen:
  port: 9000

# Correspond to your reverse proxy "listen" configuration
webserver:
  https: true
  hostname: undefined
  port: 443

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'db'
  port: 5432
  suffix: ''
  username: 'postgres'
  password: 'postgres'

# Redis server for short time storage
redis:
  hostname: 'redis'
  port: 6379
  auth: null

# From the project root directory
storage:
  avatars: '../data/avatars/'
  videos: '../data/videos/'
  logs: '../data/logs/'
  previews: '../data/previews/'
  thumbnails: '../data/thumbnails/'
  torrents: '../data/torrents/'
  cache: '../data/cache/'

log:
  level: 'info' # debug/info/warning/error

admin:
  email: null
