listen:
  port: 9000

webserver:
  https: false
  host: 'localhost'
  port: 9000

database:
  host: 'localhost'
  port: 27017
  suffix: '-dev'

# From the project root directory
storage:
  certs: 'certs/'
  uploads: 'uploads/'
  logs: 'logs/'
  thumbnails: 'thumbnails/'

network:
  friends: []

electron:
  debug: false
