listen:
  port: 9000

webserver:
  https: false
  hostname: 'localhost'
  port: 9000

database:
  hostname: 'localhost'
  port: 5432
  suffix: '_dev'
  username: 'peertube'
  password: 'peertube'

# From the project root directory
storage:
  certs: 'certs/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'
