listen:
  port: 9002

webserver:
  hostname: 'localhost'
  port: 9002

database:
  suffix: '_test2'

# From the project root directory
storage:
  certs: 'test2/certs/'
  videos: 'test2/videos/'
  logs: 'test2/logs/'
  thumbnails: 'test2/thumbnails/'
  torrents: 'test2/torrents/'

admin:
  email: 'admin2@example.com'
