listen:
  port: 9005

webserver:
  hostname: 'localhost'
  port: 9005

database:
  suffix: '_test5'

# From the project root directory
storage:
  certs: 'test5/certs/'
  videos: 'test5/videos/'
  logs: 'test5/logs/'
  thumbnails: 'test5/thumbnails/'
  torrents: 'test5/torrents/'

admin:
  email: 'admin5@example.com'
