listen:
  port: 9005

webserver:
  host: 'localhost'
  port: 9005

database:
  suffix: '-test5'

# From the project root directory
storage:
  certs: 'test5/certs/'
  uploads: 'test5/uploads/'
  logs: 'test5/logs/'
  thumbnails: 'test5/thumbnails/'
