listen:
  port: 9006

webserver:
  hostname: 'localhost'
  port: 9006

database:
  suffix: '-test6'

# From the project root directory
storage:
  certs: 'test6/certs/'
  videos: 'test6/videos/'
  logs: 'test6/logs/'
  thumbnails: 'test6/thumbnails/'
  torrents: 'test6/torrents/'
