listen:
  port: 9004

webserver:
  hostname: 'localhost'
  port: 9004

database:
  suffix: '-test4'

# From the project root directory
storage:
  certs: 'test4/certs/'
  videos: 'test4/videos/'
  logs: 'test4/logs/'
  thumbnails: 'test4/thumbnails/'
  torrents: 'test4/torrents/'
