listen:
  port: 9001

webserver:
  hostname: 'localhost'
  port: 9001

database:
  suffix: '_test1'

# From the project root directory
storage:
  certs: 'test1/certs/'
  videos: 'test1/videos/'
  logs: 'test1/logs/'
  previews: 'test1/previews/'
  thumbnails: 'test1/thumbnails/'
  torrents: 'test1/torrents/'
  cache: 'test1/cache/'

admin:
  email: 'admin1@example.com'

signup:
  limit: 4
