listen:
  port: 9003

webserver:
  hostname: 'localhost'
  port: 9003

database:
  suffix: '_test3'

# From the project root directory
storage:
  certs: 'test3/certs/'
  videos: 'test3/videos/'
  logs: 'test3/logs/'
  thumbnails: 'test3/thumbnails/'
  torrents: 'test3/torrents/'
