listen:
  port: 9004

webserver:
  host: 'localhost'
  port: 9004

database:
  suffix: '-test4'

# From the project root directory
storage:
  certs: 'test4/certs/'
  uploads: 'test4/uploads/'
  logs: 'test4/logs/'
  thumbnails: 'test4/thumbnails/'
  torrents: 'test4/torrents/'
