listen:
  port: 9001

webserver:
  hostname: 'localhost'
  port: 9001

database:
  suffix: '-test1'

# From the project root directory
storage:
  certs: 'test1/certs/'
  videos: 'test1/videos/'
  logs: 'test1/logs/'
  thumbnails: 'test1/thumbnails/'
  torrents: 'test1/torrents/'
